export const productsData = [
  {
    id: "1",
    name: "AirPods Max",
    price: 549,
    category: "Audio",
    description: "Apple-designed dynamic driver provides high-fidelity audio.",
    image: "🎧",
  },
  {
    id: "2",
    name: "Apple Watch Series 9",
    price: 399,
    category: "Wearables",
    description: "Advanced health sensors and powerful S9 SiP chip.",
    image: "⌚",
  },
  {
    id: "3",
    name: "Asus ROG Zephyrus",
    price: 1499,
    category: "Laptops",
    description: "High-performance gaming laptop with RTX 4070 graphic card.",
    image: "💻",
  },
  {
    id: "4",
    name: "Bose QuietComfort Ultra",
    price: 429,
    category: "Audio",
    description: "World-class noise cancellation and spatial listening.",
    image: "🎧",
  },
  {
    id: "5",
    name: "Dell XPS 15",
    price: 1299,
    category: "Laptops",
    description: "Stunning 3.5K OLED display and Intel Core i9 processor.",
    image: "💻",
  },
  {
    id: "6",
    name: "iPad Air",
    price: 599,
    category: "Tablets",
    description: "Supercharged by M2 chip with Liquid Retina display.",
    image: "📱",
  },
  {
    id: "7",
    name: "iPhone 15 Pro",
    price: 999,
    category: "Phones",
    description: "Aerospace-grade titanium design with A17 Pro chip.",
    image: "📱",
  },
  {
    id: "8",
    name: "Keychron K2 Keyboard",
    price: 89,
    category: "Accessories",
    description: "75% compact wireless mechanical keyboard.",
    image: "⌨️",
  },
  {
    id: "9",
    name: "Logitech MX Master 3S",
    price: 99,
    category: "Accessories",
    description: "Ergonomic wireless mouse with 8K DPI sensor.",
    image: "🖱️",
  },
  {
    id: "10",
    name: "MacBook Pro M3",
    price: 1599,
    category: "Laptops",
    description: "Mind-blowing M3 chip performance and up to 22 hours battery life.",
    image: "💻",
  },
  {
    id: "11",
    name: "Samsung Galaxy S24",
    price: 799,
    category: "Phones",
    description: "Next-generation smartphone with built-in Galaxy AI features.",
    image: "📱",
  },
  {
    id: "12",
    name: "Sony WH-1000XM5",
    price: 399,
    category: "Audio",
    description: "Industry-leading noise cancelling wireless headphones.",
    image: "🎧",
  },
];
